# group_vars/vpn_servers.yml
marzban_admin_user: marzban_admin
marzban_restore_from_s3: false
# S3 Backup settings
s3_bucket_name: "your-bucket-name"  # <-- Укажите имя вашего бакета
s3_endpoint_url: ""                 # <-- Укажите URL вашего S3 (например, https://s3.timeweb.cloud)
s3_access_key: "{{ vault_s3_access_key | default('') }}"
s3_secret_key: "{{ vault_s3_secret_key | default('') }}"
